name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl bc bison flex libelf-dev libssl-dev qemu-system-x86 apk-tools
      - name: Build kernel and initramfs
        run: |
          ./build/build_ariannacore.sh --clean
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pytest -q
